name: generate pacman game

on:
  schedule: # run automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allows to manually run the job at any time
  push: # run on every push on the master branch
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate pacman-contribution-graph.svg
        uses: sadbinsiddique/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: List generated files (debug)
        run: |
          if [ -d "dist" ]; then
            echo "dist contents:"; ls -la dist || true
          else
            echo "dist directory not present"
          fi

      - name: Create placeholder pacman graph if none generated
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls -A dist 2>/dev/null)" ]; then
            echo "No generated files found — creating placeholder SVG"
            mkdir -p dist
            cat > dist/pacman-contribution-graph.svg <<'SVG'
<svg xmlns="http://www.w3.org/2000/svg" width="600" height="120" viewBox="0 0 600 120">
  <rect width="100%" height="100%" fill="#0b0f13"/>
  <text x="20" y="40" font-family="Arial" font-size="18" fill="#9aa4b2">Pacman contribution graph (placeholder)</text>
  <text x="20" y="70" font-family="Arial" font-size="12" fill="#6b7280">The generator action was not found or failed — please check workflow logs.</text>
</svg>
SVG
          else
            echo "dist already contains files; skipping placeholder creation"
          fi

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
